GET http://localhost:3000/products

###

POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Product 1",
  "price": 100,
  "description": "Product 1 description",
  "image_url": "http://google.com"
}