POST http://localhost:8080/categories HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "name": "Category 1",
    "description": "Category 1 description"
}

###

GET http://localhost:8080/categories HTTP/1.1
Host: localhost:8080

###

GET http://localhost:8080/categories/ecde1c0e-bd7a-4dcc-a788-8aea76ee0827 HTTP/1.1
Host: localhost:8080

###

POST http://localhost:8080/products HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "name": "Product 1",
    "description": "Product 1 description",
    "price": 100,
    "category_id": "2c82ba6e-9f7d-4faf-9a20-8cd3fb915a3e",
    "image_url": "http://google.com"
}

###

GET http://localhost:8080/products HTTP/1.1
Host: localhost:8080

###

GET http://localhost:8080/products/04c4353a-3f6d-4272-a8f2-44b82c05ecc0 HTTP/1.1
Host: localhost:8080

###
GET http://localhost:8080/products/category/2c82ba6e-9f7d-4faf-9a20-8cd3fb915a3e HTTP/1.1
Host: localhost:8080
```